version: "3.8"

services:
  app:
    build:
      context: ./server
      dockerfile: DOCKERFILE
      args:
        MODE: ${MODE}
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: DOCKERFILE
      args:
        MODE: ${MODE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
